
# Project information
site_name: Spiel Stein AR
site_url: https://spielstein.ch
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - toc.integrate
  custom_dir: overrides

extra_css:
  - stylesheets/spielstein.css

plugins:
  - blog

nav:
  - Home: index.md
  - Verein: 
    - Der Verein: club/index.md
    - Mitglieder: club/mitglieder.md
    - Statuten: club/statuten.md
    - Mitglied werden: club/mitglied-werden.md
  - Blog:
    - blog/index.md