
# Project information
site_name: SpielStein
site_url: https://spielstein.ch
theme:
  name: material
  language: de
  logo: assets/logo.svg
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  custom_dir: overrides

extra_css:
  - stylesheets/spielstein.css

plugins:
  - blog

nav:
  - Home: index.md
  - Verein: club/index.md
  - Blog:
    - blog/index.md