
# Project information
site_name: Spiel Stein
site_url: https://spielstein.ch
repo_url: https://github.com/spielsteinar/spielstein.ch
repo_name: spielstein.ch
edit_uri: edit/main/docs/
theme:
  name: material
  logo: assets/logo.svg
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.indexes
    - content.tabs.link
    - content.code.copy
    - content.action.view
    - content.action.edit
    - toc.integrate
  icon:
    # https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#code-actions
    edit: material/pencil
    view: material/eye
  custom_dir: overrides    

extra_css:
  - stylesheets/spielstein.css

plugins:
  - blog
  - git-revision-date-localized:
      enable_creation_date: false
  - git-revision-date-localized:
      type: date
      format: '%d.%m.%Y'
  - git-committers:
      repository: spielsteinar/spielstein.ch
  - git-authors

nav:
  - Home: index.md
  - Verein: 
    - Der Verein: club/index.md
    - Mitglieder: club/mitglieder.md
    - Statuten: club/statuten.md
    - Mitglied werden: club/mitglied-werden.md
  - Spiele: spiele/index.md
  - Events: events/index.md
  - Blog:
    - blog/index.md

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format