
# Project information
site_name: Spiel Stein
site_url: https://spielstein.ch
theme:
  name: material
  language: de
  logo: assets/logo.svg
  favicon: assets/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
  custom_dir: overrides

extra_css:
  - stylesheets/spielstein.css

plugins:
  - blog

nav:
  - Home: index.md
  - Verein: 
    - Der Verein: club/index.md
    - Mitglieder: club/mitglied.md
    - Statuten: club/statutes.md
    - Mitglied werden: club/mitglied-werden.md
  - Blog:
    - blog/index.md